### ISSUE TITLE
Improve Read.me

### ISSUE THREAD

**Issue by jtpdev** [nihey/node-bovespa#10]
I'm studying the api, and I don't understand what the return properties mean:

```js
// {
//   id: 4851343,
//   day: '2018-04-23',
//   codbdi: '02',
//   codneg: 'ABEV3',
//   tpmerc: '010',
//   nomres: 'AMBEV S/A',
//   especi: 'ON',
//   prazot: '',
//   modref: 'R$',
//   preabe: '23.31',
//   premin: '23.23',
//   premax: '23.55',
//   premed: '23.40',
//   preult: '23.45',
//   preofc: '23.44',
//   preofv: '23.45',
//   preexe: '0.00',
//   totneg: '21813',
//   quatot: '8104000',
//   voltot: '18967719600',
//   indopc: '0',
//   fatcot: '0000001',
//   ptoexe: '0000000000000',
//   codisi: 'BRABEVACNOR1',
//   dismes: '119',
//   datven: '9999-12-31',
//   created_at: '2019-04-01T12:25:13.439Z',
//   updated_at: '2019-04-01T12:25:13.439Z'
// }
```

It's in read.me but, for example: what is **preofc** and **preofv**?
What is the value of closing?

**Comment by nihey** [comment]
@jtpdev All of those labels are replicas of the original Bovespa Historic Values file, you can take a look at: http://bvmf.bmfbovespa.com.br/pt-br/download/SeriesHistoricas_Layout.pdf for more information.

From that, I believe the closing value would be: `preult`

**Comment by jtpdev** [comment]
Thanks @nihey, it's in documentation? I didn't found it.

**Comment by nihey** [comment]
@jtpdev It is currently not, but I'll add it soon!
