### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by jtpdev** [nihey/node-bovespa#9]
I'm trying to use only https://bovespa.nihey.org (https://bovespa.nihey.org/api/quote/ABEV3/2018-02-14) but I'm blocked by CORS policy.

I tried to use https://github.com/corihudson/crossorigin.me to workarround this but didn't work.

**Comment by nihey** [comment]
Thanks for reporting that @jtpdev I'll look into it this week, it should be a quick fix.
